name: Deploy Backend via CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy CDK Stack
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::828244906528:role/GitHubActionDeployRole 
          aws-region: us-east-1 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Deploy with AWS CDK
        run: npx cdk deploy --all --require-approval never